# Generated by Django 5.2.17 on 2026-09-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('property_name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=125, null=True)),
                ('country', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'db_table': 'tbl_properties',
            },
        ),
    ]
