# Generated by Django 5.2.17 on 2026-09-11 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('unit_number', models.CharField(max_length=100)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('occupied', 'Occupied')], max_length=20, null=True)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.properties')),
            ],
            options={
                'db_table': 'tbl_units',
            },
        ),
    ]
