# Generated by Django 5.2.17 on 2026-09-11 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logged_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='members.members')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='units.units')),
            ],
            options={
                'db_table': 'tbl_contracts',
            },
        ),
    ]
